# Generated by Django 4.2.8 on 2025-04-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_events/'),
        ),
    ]
