# Generated by Django 4.2.8 on 2025-04-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_review_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
    ]
