services:
  - type: web
    name: myday
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn myday.wsgi:application --workers=2 --threads=2 --timeout=60 --log-file=-"
    healthCheckPath: /health/
    autoDeploy: true
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "myday.settings_render"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com,.onrender.com,myday-gla-dsuw.onrender.com,localhost,127.0.0.1"
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: myday_db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

databases:
  - name: myday_db
    databaseName: myday
    plan: free
