services:
  # A Django web service
  - type: web
    name: myday
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn myday.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DATABASE_URL
        fromDatabase:
          name: myday_db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

  # A PostgreSQL database
  - type: pserv
    name: myday_db
    env: docker
    plan: free
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
